# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  # Default build command.
  command = "echo 'default context'"

# Production context: all deploys from the Production branch set in your site’s
# deploy contexts will inherit these settings.
[context.production]
  command = "quasar build"
  FIREBASE_API_KEY = "firebaseapikey" 
